server:
  port: 0


spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/commerce
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true