grpc:
  server:
    port: 59091


collector:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      topic-sensor: "telemetry.sensors.v1"
      topic-hub: "telemetry.hubs.v1"
      properties:
        key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
        value.serializer: "serializer.GeneralAvroSerializer"